### ISSUE TITLE
Coredump when receiving certain uci position notation

### ISSUE THREAD

**Issue by kyleaforrester** [KierenP/Halogen#178]
Hi Keiren,

Halogen coredumps when receiving the uci position command when both the initial position and the 'moves' are given at once.  This is causing cutechess to error out when using Halogen.  Curiously, I would have expected you to run into this issue while using cutechess as part of OpenBench.  Here is how to reproduce:

kyle@kyle-ubuntu:~/Chess/Halogen/Halogen/src$ ./Halogen-x64-pext-avx2.exe
Halogen 8.1 x64 POPCNT
uci
id name Halogen 8.1
id author Kieren Pearson
option name Clear Hash type button
option name Hash type spin default 2 min 2 max 262144
option name Threads type spin default 1 min 1 max 256
option name SyzygyPath type string default <empty>
uciok
isready
readyok
position startpos
go depth 12
info depth 1 seldepth 1 score cp 59 time 1 nodes 0 nps 0 hashfull 0 tbhits 0 pv e2e3
info depth 2 seldepth 2 score cp 26 time 1 nodes 0 nps 0 hashfull 0 tbhits 0 pv e2e3 d7d5
info depth 3 seldepth 4 score cp 50 time 2 nodes 0 nps 0 hashfull 1 tbhits 0 pv e2e3 d7d5 d2d4
info depth 4 seldepth 5 score cp 30 time 2 nodes 0 nps 0 hashfull 1 tbhits 0 pv e2e3 d7d5 d2d4 e7e6
info depth 5 seldepth 7 score cp 55 time 3 nodes 4096 nps 1365000 hashfull 6 tbhits 0 pv d2d4 e7e6 e2e4 d7d5 b1c3
info depth 6 seldepth 8 score cp 40 time 6 nodes 8192 nps 1365000 hashfull 9 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 b1c3 a7a6
info depth 7 seldepth 10 score cp 50 time 14 nodes 28672 nps 2048000 hashfull 34 tbhits 0 pv d2d4 d7d5 e2e3 g7g6 c2c4 f8g7 b1c3
info depth 8 seldepth 11 score cp 30 time 25 nodes 61440 nps 2457000 hashfull 61 tbhits 0 pv d2d4 d7d5 e2e3 g8f6 c2c4 b8c6 g1f3 c8g4
info depth 9 seldepth 14 score cp 49 time 43 nodes 110592 nps 2571000 hashfull 121 tbhits 0 pv d2d4 d7d5 e2e3 e7e6 c2c4 f8e7 b1c3 a7a6 g1f3
info depth 10 seldepth 16 score cp 36 time 70 nodes 192512 nps 2750000 hashfull 198 tbhits 0 pv d2d4 d7d5 e2e3 g8f6 c2c4 d5c4 f1c4 b8c6 g1f3 c8g4
info depth 11 seldepth 16 score cp 42 time 160 nodes 475136 nps 2969000 hashfull 417 tbhits 0 pv d2d4 g8f6 c2c4 g7g6 b1c3 d7d6 g1f3 f8g7 e2e4 e8g8 e4e5
info depth 12 seldepth 19 score cp 46 time 306 nodes 921600 nps 3011000 hashfull 741 tbhits 0 pv e2e4 c7c5 b1c3 b8c6 g1f3 e7e6 d2d4 c5d4 f3d4 g8f6 d4c6 d7c6
bestmove e2e4
position startpos moves e2e4 d7d5
go depth 12
Segmentation fault (core dumped)

Are you able to reproduce this as well?

**Comment by KierenP** [comment]
Hi Kyle, thank you very much for bringing that to my attention. Correct me if I am wrong but this crash originated from a compile of Halogen you made yourself recently from the master branch? I get the exact same output as you when I compile 7671590c6bba74557b1a1cd4dc3cd5246e31ab73.

```
Halogen 8.1 x64 POPCNT AVX2
uci
id name Halogen 8.1
id author Kieren Pearson
option name Clear Hash type button
option name Hash type spin default 2 min 2 max 262144
option name Threads type spin default 1 min 1 max 256
option name SyzygyPath type string default <empty>
uciok
isready
readyok
position startpos
go depth 12
info depth 1 seldepth 1 score cp 59 time 0 nodes 0 nps 0 hashfull 0 tbhits 0 pv e2e3
info depth 2 seldepth 2 score cp 26 time 0 nodes 0 nps 0 hashfull 0 tbhits 0 pv e2e3 d7d5
info depth 3 seldepth 4 score cp 50 time 16 nodes 0 nps 0 hashfull 1 tbhits 0 pv e2e3 d7d5 d2d4
info depth 4 seldepth 5 score cp 30 time 16 nodes 0 nps 0 hashfull 1 tbhits 0 pv e2e3 d7d5 d2d4 e7e6
info depth 5 seldepth 7 score cp 55 time 16 nodes 4096 nps 256000 hashfull 6 tbhits 0 pv d2d4 e7e6 e2e4 d7d5 b1c3
info depth 6 seldepth 8 score cp 40 time 16 nodes 8192 nps 512000 hashfull 9 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 b1c3 a7a6
info depth 7 seldepth 10 score cp 50 time 31 nodes 28672 nps 924000 hashfull 34 tbhits 0 pv d2d4 d7d5 e2e3 g7g6 c2c4 f8g7 b1c3
info depth 8 seldepth 11 score cp 30 time 47 nodes 61440 nps 1307000 hashfull 61 tbhits 0 pv d2d4 d7d5 e2e3 g8f6 c2c4 b8c6 g1f3 c8g4
info depth 9 seldepth 14 score cp 49 time 94 nodes 110592 nps 1176000 hashfull 121 tbhits 0 pv d2d4 d7d5 e2e3 e7e6 c2c4 f8e7 b1c3 a7a6 g1f3
info depth 10 seldepth 16 score cp 36 time 156 nodes 192512 nps 1234000 hashfull 198 tbhits 0 pv d2d4 d7d5 e2e3 g8f6 c2c4 d5c4 f1c4 b8c6 g1f3 c8g4
info depth 11 seldepth 16 score cp 42 time 344 nodes 475136 nps 1381000 hashfull 417 tbhits 0 pv d2d4 g8f6 c2c4 g7g6 b1c3 d7d6 g1f3 f8g7 e2e4 e8g8 e4e5
info depth 12 seldepth 19 score cp 46 time 656 nodes 921600 nps 1404000 hashfull 741 tbhits 0 pv e2e4 c7c5 b1c3 b8c6 g1f3 e7e6 d2d4 c5d4 f3d4 g8f6 d4c6 d7c6
bestmove e2e4
```

Does the crash occur for you always or only rarely? I was unable to reproduce the crash.

Does the crash still occur when you use the most up to date Halogen from the master branch?

**Comment by kyleaforrester** [comment]
Hi Kieren,
Yes the crash is reproducible.  I just reproduced on commit hash 86ddeedd4.  To further specify, the crash happens for the second position command, not the first one.  In your attempted reproduction you only ran the position command once.  Please see the below output I just reproduced with:

kyle@kyle-ubuntu:~/Chess/Halogen/Halogen/src$ ./Halogen-x64-pext-avx2.exe
Halogen 8.1 x64 POPCNT
uci
id name Halogen 8.1
id author Kieren Pearson
option name Clear Hash type button
option name Hash type spin default 2 min 2 max 262144
option name Threads type spin default 1 min 1 max 256
option name SyzygyPath type string default <empty>
uciok
isready
readyok
position startpos moves e2e4 e7e5
go depth 10
info depth 1 seldepth 1 score cp 43 time 0 nodes 0 nps 0 hashfull 0 tbhits 0 pv d2d4
info depth 2 seldepth 4 score cp 9 time 0 nodes 0 nps 0 hashfull 0 tbhits 0 pv d2d4 e5d4 d1d4
info depth 3 seldepth 5 score cp 15 time 1 nodes 0 nps 0 hashfull 1 tbhits 0 pv c2c3 d7d5 d2d4 d5e4 d4e5
info depth 4 seldepth 8 score cp 12 time 1 nodes 0 nps 0 hashfull 2 tbhits 0 pv g1f3 g8f6 d2d4 e5d4 d1d4
info depth 5 seldepth 9 score cp 24 time 2 nodes 0 nps 0 hashfull 3 tbhits 0 pv g1f3 b8c6 b1c3 f8c5 f1c4
info depth 6 seldepth 10 score cp 4 time 4 nodes 8192 nps 2048000 hashfull 6 tbhits 0 pv g1f3 b8c6 b1c3 f8c5 d2d3 g8f6
info depth 7 seldepth 15 score cp 16 time 6 nodes 16384 nps 2730000 hashfull 9 tbhits 0 pv g1f3 b8c6 d2d4 e5d4 f3d4 c6d4 d1d4
info depth 8 seldepth 13 score cp 10 time 12 nodes 32768 nps 2730000 hashfull 21 tbhits 0 pv g1f3 b8c6 f1b5 g8f6 b1c3 c6d4 b5c4 d7d6
info depth 9 seldepth 17 score cp 32 time 33 nodes 98304 nps 2978000 hashfull 72 tbhits 0 pv g1f3 g8f6 f3e5 f6e4 d2d4 d7d6 e5f3 b8c6 f1d3
info depth 10 seldepth 14 score cp 17 time 53 nodes 163840 nps 3091000 hashfull 131 tbhits 0 pv g1f3 g8f6 f3e5 f6e4 d2d4 d7d6 e5f3 b8c6 f1d3 d6d5
bestmove g1f3
position startpos moves e2e4 e7e5 g1f3 g8f6
go depth 10
Segmentation fault (core dumped)



Please note that I have tested these same UCI commands with other engines (weiss, stockfish) and they handle the scenario correctly.

**Comment by KierenP** [comment]
My mistake, I didn't the extra commands at the bottom. I'm still struggling to reproduce the crash on my computer. These are the steps I followed:

1. I made a static compile of Halogen master branch (86ddeed) with `make release` 
2. Ran Halogen-x64-pext-avx2.exe
3. Inputted commands:
    - uci
    - isready
    - position startpos moves e2e4 e7e5
    - go depth 10
    - position startpos moves e2e4 e7e5 g1f3 g8f6
    - go depth 10

No crash occurs for me. Can I please have some more details? What operating system are you running on and what compiler version are you using?

**Comment by theo77186** [comment]
Can reproduce the crash, known gcc/libpthread issue. I somehow managed to reproduce the crash but only with static builds and I got this stack trace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00000000004a4a73 in std::thread::join() ()
#2  0x0000000000407918 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:124
```
which points me directly to the gcc/libpthread issue. A workaround would be compiling with `-Wl,--whole-archive -lpthread -Wl,--no-whole-archive`. It's also possible to use dynamic builds with `make` or `make pgo`.

**Comment by KierenP** [comment]
@kyleaforrester can you confirm the work around worked for you?

**Comment by kyleaforrester** [comment]
Hi Kieren,
Yes, this workaround worked for me! I have no idea how theo figured this out.  This was the command I used for compilation:

g++ -O3 -Wall -Wextra -Wshadow -std=c++14 -DNDEBUG -flto -static -fno-devirtualize *.cpp -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -lm -msse -msse3 -mpopcnt -mavx2 -msse4.1 -mssse3 -msse2 -DUSE_POPCNT -msse3 -mpopcnt -DUSE_PEXT -mbmi2 -o Halogen-x64-pext-avx2.exe

I am opening up a pull request in case you wish to take this change into the repo.

Thanks,
Kyle
