### ISSUE TITLE
using engine-vs-engine GUI : how is best move determined ?

### ISSUE THREAD

**Issue by tissatussa** [KierenP/Halogen#248]
I have another question about the functioning / performance of Halogen. First we had issue #239 : "develop engine with well chosen positions ?" (see https://github.com/KierenP/Halogen/issues/239) and regarding this I did some testing with the Halogen v9 MPV version and other engines, which made me wonder other issues regarding the functioning of MPV.

when doing a match between 2 engines in CuteChess, given a particular start position, i often set the time limit to 10 minutes for the whole game, plus 10 seconds bonus per move .. it seems engines have different time management : after a few moves, some engines have used almost all their time (esp. SF and its forks!) and then uses their 10 seconds for each move .. NOTE: using CuteChess, or another GUI, MPV should be 1 (so: no MPV) -- higher MPV values may lead to malfunctioning, the authors of CuteChess pointed that out in one of my other chess engine "discussions" on GitHub. Engines give their best move when time is up or it estimates the remaining time is insufficient to calculate a next dp. But it appears a "best move" might not be accurate .. i conclude this while using MPV to analyse a position, although i have no clue how the calculation process differs from MPV 1 when doing an engine-vs-engine match.

while testing a position with a single engine in SCID or another GUI (no CuteChess), using MPV more than 1, it takes some time for an engine to evaluate all MPV moves at each depth (dp) before that dp is 'finished' .. when cancelling the evaluation process, not all MPV moves of the current dp will be calculated yet, but the engine comes up with a "best move" .. it appears that many engines show the best move of their latest finished dp, but some engines give the eval of their current dp, which may result in a "best move" which was not the top move of the latest finished dp .. this way, sometimes even a doubtful "best move" is given! I consider this is not good practice .. Halogen v9 MPV also suffers this behaviour .. i think the proper implementation of the MPV functionality  --although used for analyses, not engine-vs-engine play--  is this : when the calculations are stopped, because time is up or insufficient or the user cancels, the best move should be the top move of the latest finished dp.

I will give an example. Consider a position from the recent game Tari vs Firouzja, Tata Steel Chess tournament 2021 (see the 'PowerPlayChess' video https://www.youtube.com/watch?v=US3SW4E8mcs ) :

![Screenshot_2021-01-20_14-30-48 Halogen Tari - Firouzja](https://user-images.githubusercontent.com/1109281/105181611-518fcf80-5b2c-11eb-8154-bbfba00c2631.png)

1k6/pp4p1/2qNp3/2p1P1bP/3r1nb1/1PR1QN2/P6P/5RK1 w - - 0 1
What should White play ?

here certainly (although not obvious) the best move is Kh1 (!), which Halogen v9 MPV tends to, but when it's busy calculating dp 23 (which will take more than 30 seconds for all MPV moves to be completed) and i cancel the process, Halogen gives h4 as "best move" !?

here is a short screencast of CEAC, my own GUI "Chess Engine Analysing Chart", which clearly shows how we can capture the UCI log and create statistics :

https://user-images.githubusercontent.com/1109281/105181860-a16e9680-5b2c-11eb-9233-6f5d5d78cd5b.mp4

I could elaborate about the way other engines behave, but i think this example and my above explanation show how delicate the determination of the "best move" is. When we use CuteChess for engine-vs-engine play, were the functioning of an engine comes to practice, giving a 'doubtful' best move like h4 might lose a game! How can we know the way an engine decides its best move when doing a match, using MPV 1 ?

**Comment by KierenP** [comment]
Thank you for reporting this. The issue should be fixed as of (https://github.com/KierenP/Halogen/pull/249).

**Comment by tissatussa** [comment]
i did some tests with your newest version and yes, the MPV issue is solved. Great job. Your code must be well made : during compilation i don't see a single warning etc. while many other engines have those during comilation -- however, most of them do compile OK, despite those warnings. You also seem to detect an (optimal) architecture of the user machine .. doing 'make' to compile, many other engines demand the parameters 'build' and 'ARCH=' .. can you elaborate on this?  Maybe even note this in the Readme.md 

the following points are somewhat beside the scope of the current issue, but i want to mention them here :

* you could use "subsection numbering" for the version, eg. Halogen version 9 could be v9.1 or v9.249 .. this could also be shown in the concerning UCI line.  I think this is simple but gives much more clearity.

* the default Hash value is 2 Mb .. we already discussed this issue briefly and you pointed out a GUI should show the Hash is filled about 50% .. you could give the user an explanation how to set a proper Hash value and maybe provide a test procedure to determine an optimal setting. I have no clue how the evaluation differs when the Hash value differs ..

* during / after compilation it seems Halogen tests itself by evaluation of some position(s) and displaying variations which increase in length and finish with a best move .. i compiled several other engines but i never saw such output .. it's OK, but what is happening then ?

**Comment by KierenP** [comment]
> * during / after compilation it seems Halogen tests itself by evaluation of some position(s) and displaying variations which increase in length and finish with a best move .. i compiled several other engines but i never saw such output .. it's OK, but what is happening then ?

Halogen by default uses PGO (profile guided optimization). Basically it compiles the program, runs it through test positions which is what you're seeing, and then recompiles using the information it gathered.

> * you could use "subsection numbering" for the version, eg. Halogen version 9 could be v9.1 or v9.249 .. this could also be shown in the concerning UCI line.  I think this is simple but gives much more clearity.

Starting with Halogen 10 I am hoping to use a better versioning system.

> * the default Hash value is 2 Mb .. we already discussed this issue briefly and you pointed out a GUI should show the Hash is filled about 50% .. you could give the user an explanation how to set a proper Hash value and maybe provide a test procedure to determine an optimal setting. I have no clue how the evaluation differs when the Hash value differs ..

I'll eventually get around to explaining the main uci settings in the readme.
