### ISSUE TITLE
Two functions implemented in the same way

### ISSUE THREAD

**Issue by thehlopster** [KierenP/Halogen#253]
It is odd that the body of '>' function is fully equivalent to the body of '<' function.
[First](https://github.com/KierenP/Halogen/blob/master/Halogen/src/MoveGenerator.h#L20)
[Second](https://github.com/KierenP/Halogen/blob/master/Halogen/src/MoveGenerator.h#L21)
I think it should be: `bool operator>(const ExtendedMove& rhs) const { return score > rhs.score; };`

**Comment by KierenP** [comment]
Great catch! Fixed in https://github.com/KierenP/Halogen/pull/254. Thanks :)
