### ISSUE TITLE
no pondering ?

### ISSUE THREAD

**Issue by tissatussa** [KierenP/Halogen#260]
While i let Halogen play games against another engine with CuteChess, it seems not to use pondering. CuteChess has a general option "thinking on opponent's time", which i switched ON, but the evaluation panel shows Halogen does no calculating when the other engine is calculating its move.

In practice pondering can be useful : with each calculated move comes an optimal variation including the expected counter-move, which is used while pondering, and if that move indeed is played by the other engine, less (or no) time has to be spend to calculate the next move. 

NOTE: I have no clue how an engine decides the (max) amount of seconds to use for a move in a certain time format, but with pondering more time remains on the clock for an engine to play the game .. why not use this (CuteChess) feature ?

**Comment by KierenP** [comment]
Pondering is hard to implement and in almost all engine tournaments pondering is switched off. It's for this reason the functionality has never been added to Halogen. I do not have plans to add it for the foreseeable future.
