### ISSUE TITLE
apply Alexander Shashin chess method ?

### ISSUE THREAD

**Issue by tissatussa** [KierenP/Halogen#261]
hi, i gather many chess engines and test them, eg. using CuteChess to play engine-vs-engine matches .. for some time now, my best engine is ShashChess, see https://github.com/amchess/ShashChess/ .. it almost never loses and calculates very fast.

ShashChess is derived from StockFish but has a special architecture which is based on the chess theory of Alexander Shashin .. i did not study this, but you can read his book:

**Best Play: A New Method For Discovering The Strongest Move Paperback**
July 16, 2013 - by Alexander Shashin
https://www.amazon.com/Best-Play-Method-Discovering-Strongest/dp/1936277468

_Have you ever wished for a “formula” to help you decide what move to make in any given chess position? In this ambitious and groundbreaking work, physicist and chess master Alexander Shashin presents the fruit of three decades of research into the elements of the game. He breaks down the position into mathematical ratios that compare the fundamental factors of material, mobility, safety, and space for each side, leading you to the proper plan and the mental attitude to adopt in light of what’s happening on the board._

_Relying on the games of three world champions with distinctive playing styles – Tal, Capablanca, and Petrosian – and backed up by personal and computer-aided analysis, Best Play explains how Shashin’s approach works in practice to guide your decisions in all kinds of situations, including those too wild and murky to provide clear-cut conclusions. Some 125 high-level examples are followed by 125 exercises with solutions to help you learn the method._

_Not just a textbook for the chess scientist to ponder in the lab, Best Play offers a fully formed philosophy of the game to prepare the chess warrior for any kind of battle._

**Comment by KierenP** [comment]
While *Best Play: A New Method For Discovering The Strongest Move* would probably make me a better chess player, I doubt it would make me a better chess programmer. 

Halogen uses a neural network, and so I have very little ability to augment its current evaluation and to add new terms. This is something that is unlikely to change.
