### ISSUE TITLE
material vs development

### ISSUE THREAD

**Issue by tissatussa** [KierenP/Halogen#284]
hi,

i did engine (vs engine) tests in this unbalanced opening position, Black to move :

rnbqk1nr/ppp2p1p/3ppbp1/8/2B1P2P/2N2Q2/PPP1NPP1/R1B1K2R b KQkq - 0 3

![Screenshot_2021-03-14_15-58-16](https://user-images.githubusercontent.com/1109281/111073846-aaeafe00-84e0-11eb-8a77-779c3e66e571.png)

it's a position from a rare gambit which i recently found by this GothamChess video on YT:

**THE MONKEY'S BUM | TRICKY CHESS GAMBIT**
Published Nov 5, 2020
https://www.youtube.com/watch?v=RoZwWjb1--s

in this position, many SF-based engines like to storm with the h-pawn and play aggressive with White, often sacrificing more pawns to keep initiative and create tactical threats, leaving Black with a weak King and an unharmonious position were too many pieces have no space and time to develop .. however, strong engines with Black manage to defend the extra pawn by a quick d7-d6 and a clever piece development and can produce a win ..

Halogen 10.4 takes the bite : Bxh4 ?!
Halogen seems too focussed on winning material here, disregarding development .. many other strong engines prefer to develop other pieces. 

here's a game (7 min + 7 sec bonus) done in CuteChess :

[Event "engine-vs-engine"]
[Site "Holland"]
[Date "2021.03.14"]
[White "SF SugaR-AI v1.40"]
**[Black "Halogen v10.4"]**
[Result "1-0"]
[FEN "rnbqk1nr/pppp1p1p/4p1p1/8/2BbP3/5Q2/PPP1NPPP/RNB1K2R b KQkq - 0 1"]
[GameDuration "00:14:48"]
[PlyCount "72"]
[SetUp "1"]
[TimeControl "420+7"]

1... Bf6 {+0.64/24 20s} 2. Nbc3 {-1.12/31 46s} d6 {+0.68/24 14s}
3. h4 {-1.27/30 0s} Bxh4 {+0.80/23 14s} 4. e5 {-0.87/25 9.7s}
dxe5 {+0.61/27 14s} 5. Be3 {-0.62/30 30s} a6 {+1.07/23 22s} 6. Rd1 {0.00/30 22s}
Nd7 {+0.86/24 19s} 7. Ne4 {-0.30/30 0s} Qe7 {+0.97/25 18s}
8. Rxh4 {+1.43/30 8.4s} Qxh4 {0.00/32 13s} 9. Bg5 {+1.32/33 1.5s}
Qh1+ {0.00/36 12s} 10. Kd2 {+1.11/35 1.7s} Qh2 {0.00/37 20s}
11. Kc1 {+0.99/34 0.34s} h6 {0.00/28 12s} 12. Bd8 {+0.81/38 18s}
f5 {0.00/33 24s} 13. Bxe6 {+0.84/37 15s} Qh5 {-1.30/27 22s}
14. Qg3 {+0.79/38 4.1s} Kxd8 {-1.49/31 20s} 15. Bxd7 {+0.85/39 0.001s}
Bxd7 {-1.46/33 15s} 16. Qxe5 {+0.80/39 7.7s} fxe4 {-1.64/32 22s}
17. Qxh8 {+0.88/40 26s} g5 {-1.38/31 14s} 18. Qxg8+ {+0.85/37 14s}
Qe8 {-1.34/29 12s} 19. Qg7 {+0.77/38 4.5s} Kc8 {-1.23/27 12s}
20. Rd5 {+1.20/29 17s} b6 {-1.10/32 14s} 21. Re5 {+1.93/30 14s}
Qh5 {-0.27/27 12s} 22. Nd4 {+2.35/30 12s} Bb5 {-1.13/24 11s}
23. Qg8+ {+5.55/29 12s} Kb7 {-2.21/27 12s} 24. Qd5+ {+5.74/30 2.3s}
Ka7 {-2.05/29 14s} 25. b3 {+5.91/30 0.38s} Rc8 {-2.65/26 14s}
26. Re7 {+6.14/29 18s} Kb8 {-2.72/31 19s} 27. Ne6 {+6.75/29 13s}
Qh2 {-4.33/27 22s} 28. Nd8 {+49.19/33 12s} Bc6 {-24.74/29 12s}
29. Nxc6+ {+M17/57 13s} Ka8 {-32.81/33 17s} 30. Kb1 {+M15/64 0s}
Qf4 {-M20/25 18s} 31. g4 {+M13/72 14s} b5 {-34.96/30 20s} 32. Re8 {+M11/83 13s}
Qf5 {-M10/60 10s} 33. gxf5 {+M9/175 13s} Kb7 {-M8/78 9.8s} 34. Nd8+
Kb6 {-M6/99 1.2s} 35. Qc6+ Ka5 {-M4/99 0.013s} 36. Nb7+ Kb4 {-M2/99 0.006s}
37. Qc5# {White mates} 1-0

**Comment by KierenP** [comment]
You're right, Halogen wants to play Bxh4 which according to Stockfish is not a good move. I'll have to do some further investigation into what Halogen appears not to see.

**Comment by tissatussa** [comment]
it's a typical position regarding the old theme "material vs development" and space & tempo .. i have no clue how Halogen' pruning and evaluation is done (regardless the playtime, Halogen also likes to take the pawn at greater depths in this position) but its main attitude is questioned here (all fair though).  I might find other typical positions of this theme .. are you interested ?  I recently discovered that EPD lists of FEN positions exist to test engines .. how does that work ?  I found such EPDs but no info about using them ..

**Comment by tissatussa** [comment]
here's another game and position, which suits the theme of this issue :

rnb1k2r/ppp1n1pp/3ppq2/5p2/2PPP3/3B1N2/PP1N1PPP/R2QK2R w KQkq - 4 8

![Screenshot_2021-03-18_00-37-18](https://user-images.githubusercontent.com/1109281/111553326-6da69a80-8784-11eb-9693-0fb773f5824f.png)

this is a position from a recent engine-vs-engine test with Halogen v9 #248 .. playtime 10 minutes +10 sec bonus .. i also made a video of it:

**Chess intothe fire**
https://www.bitchute.com/video/diNSrzoOGY2V/

Chess game with animation. Two very strong chess engines are playing : Halogen v9 (White) and ShashChess v15.1 NNUE (Black). I gave them the start position after 4...f5, which is dubious, but black wins nicely, being the strongest of the two.

Only strong engines (like SF family) consider a Black setup with 5...d6 followed by Qf6! And Halogen does not take on f5 .. ShashChess (v15.1 with almost 3500 rating) uses the g-pawn for attack when Halogen decides the poor (?!) move 8. O-O , sacrifices a pawn, takes space and gets initiative with long term advantage .. note that Halogen was not the only engine to lose with White against ShashChess, although White starts with around +0.8 ..

i hope this example makes sense and helps to develop Halogen.

---

Music: "Into the fire" by Deep Purple
2021@ArtFlow - all rights respected

[Event "engine vs engine"]
[Site " https://lichess.org/F8S8U6vX/black "]
[Date "2021.01.29"]
[White "Halogen v9 MPV #249"]
[Black "ShashChess v15.1 NNUE"]
[Result "0-1"]

1. d4 e6 2. c4 Bb4+ 3. Bd2 Bxd2+ 4. Nxd2 f5 5. e4 d6 6. Bd3 Qf6 7. Ngf3 Ne7 8. O-O O-O 9. Rc1 g5 10. d5 g4 11. Ne1 Ng6 12. dxe6 f4 13. Qxg4 Bxe6 14. Qe2 c5 15. Ndf3 Nc6 16. Qd2 Rae8 17. Rd1 Nge5 18. b3 b6 19. Be2 Re7 20. a4 Kh8 21. Kh1 Rg7 22. a5 Nxa5 23. Qxd6 Nxf3 24. Nxf3 Nxb3 25. e5 Qf7 26. Qd3 Na5 27. Rc1 Rg6 28. Nh4 Rh6 29. Nf3 Bg4 30. Qc3 Nc6 31. Rcd1 Nd4 32. Rxd4 cxd4 33. Qxd4 Qg7 34. Re1 a5 35. c5 bxc5 36. Qxc5 Rg8 37. Qc3 Bc8 38. Rg1 Bb7 39. Ne1 a4 40. Bd1 Rh4 41. Bxa4 Rc8 42. Qxc8+ Bxc8 43. Nf3 Rh6 44. Bb3 Rb6 45. Rd1 Qc7 46. Bd5 Qc2 47. Rg1 Qc5 48. Be4 Rb4 49. Re1 Kg7 50. Kg1 Ba6 51. h3 Rb2 52. Kh1 Qxf2 53. Rg1 Bc8 54. Ne1 Qg3 55. Nf3 Kf8 56. Nh2 Bxh3 57. Bf3 Bxg2+ 58. Bxg2 Rf2 59. e6 Ke7 60. Nf1 Qh4+ 61. Nh2 f3 62. Ra1 Rxg2 63. Ra7+ Kf6 64. Rf7+ Kg6 65. Rxh7 Qxh7 66. e7 Qxh2# { Black wins by checkmate. } 0-1

**Comment by KierenP** [comment]
Closing this issue for now. If you find positions where Halogen plays a clear blunder please reopen and post them here.
