### ISSUE TITLE
Build Fail On Windows

### ISSUE THREAD

**Issue by SwiftGodDev** [KierenP/Halogen#309]
Hi, I tried to build Halogen using MSVS 2019. However **HalogenTests.vcxproj** project fails to build with this error:

C2665 : 'LegalMoves': none of the 2 overloads could convert all the argument types.

**Comment by KierenP** [comment]
Hi, yes the unit tests are broken at the moment, sorry about that!

If you are just wanting to compile Halogen for yourself, don’t worry about
that. You can just compile the build Halogen.vcxproj and ignore the unit
test project.

I’ve been thinking of removing the unit tests. They don’t have enough
coverage and aren’t very useful.
