### ISSUE TITLE
FRC support?

### ISSUE THREAD

**Issue by CMCanavessi** [KierenP/Halogen#344]
Do you have plans for supporting FRC? It's becoming popular and even TCEC now has an FRC event.

**Comment by KierenP** [comment]
FRC has been on my TODO list for some time, but at the moment it is not a top priority.

**Comment by KierenP** [comment]
As of 63ca884d5f6554743c4348d0e73ccdd208891dce (Halogen 11.4) FRC is supported in Halogen.

If you're able, please build Halogen and test it out. Also please feel free to reach out if you encounter any bugs or issues. Thanks :)
