### ISSUE TITLE
`open` and `showModal` are missing for `dialog`

### ISSUE THREAD

**Issue by jquesada2016** [KierenP/Halogen#400]
I saw that `diallog` had an `open` row in it's attribute row type. However, I don't see any functions to create the `open` attribute for the dialog element.

Also, `showModal` would be a great addition, although it is neither a property nor an attribute, as per the spec, but it might not be a bad idea to add it as a helper prop where the VDom can call `.showModal()` and `.close()` on the element as the prop is added/removed.

**Comment by KierenP** [comment]
I think you’ve opened an issue in the wrong repo. Maybe [this Halogen?](https://github.com/purescript-halogen/purescript-halogen)

**Comment by jquesada2016** [comment]
Yes! Very sorry!
