### ISSUE TITLE
Halogen 2.7.3 - 2.8.2a

### ISSUE THREAD

**Issue by yellow-panther** [KierenP/Halogen#5]
Hello KierenP,

cf. Günther´s thread on http://talkchess.com/forum3/viewtopic.php?f=2&t=69754&start=440#p823177 For v2.7-2.8.2a vcruntime 140_1.dll - seems that
[vcruntime140_1.zip](https://github.com/KierenP/Halogen2/files/4005346/vcruntime140_1.zip) is required

v2.5.1 uci >enter key > 2,4,1
v2.6.2 uci > enter key > 2.6.1
v2.8.2a uci > enter key > 2,7.3

Indeed very confusing - which is your current edition?
Norbert

**Comment by KierenP** [comment]
Hi, I understand that the way I have managed the binaries is non-standard. I usually forget to update the version text output in the binaries when I make new releases. Please go by the version number for the releases to see what the latest version is (Halogen2-7-3.exe is the latest release).

As for the vcruntime, I am not sure what is going on with that. I googled it and it seems that you will need to download the required dll?
